### ISSUE TITLE
Remaining deprecation: "Psr\Container\ContainerInterface" autowiring alias is deprecated

### ISSUE THREAD

**Issue by axi** [php-translation/symfony-bundle#455]
Using latest symfony & symfony-bundle, I still have a deprecation warning
> Since symfony/dependency-injection 5.1: The "Psr\Container\ContainerInterface" autowiring alias is deprecated. Define it explicitly in your app if you want to keep using it. It is being referenced by the "Translation\Bundle\Controller\WebUIController" service.

**Comment by bocharsky-bw** [comment]
Was fixed in #459

**Comment by axi** [comment]
`WebUIController` still extends `AbstractController`, sorry not fixed

**Comment by bocharsky-bw** [comment]
Hey @axi , please, take a look at #460 as a possible fix. Can we close this issue with it completely?

**Comment by bocharsky-bw** [comment]
Thanks for confirming it worked for you!
